openapi: 3.0.0
info:
  title: DevServer API
  description: API documentation for the DevServer endpoints.
  version: 1.0.0
paths:
  /accounts:
    get:
      summary: Get all accounts
      description: Retrieve the list of accounts available in the DevNode.
      operationId: getAccounts
      tags:
        - accounts
      responses:
        '200':
          description: A list of accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    address:
                      type: string
                    privateKey:
                      type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /dev-account:
    get:
      summary: Get Dev Account Info
      description: Retrieve information about the dev account on the Ethereum network.
      operationId: getDevAccount
      tags:
        - dev-account
      responses:
        '200':
          description: Dev account info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  balance:
                    type: number
                    format: float
        '500':
          description: Internal server error

  /send-tx:
    post:
      summary: Send a transaction
      description: Send a transaction to the Ethereum network.
      operationId: sendTransaction
      tags:
        - transactions
      requestBody:
        description: Transaction data
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                value:
                  type: string
                gas:
                  type: string
                data:
                  type: string
      responses:
        '200':
          description: Transaction sent successfully.
        '400':
          description: Invalid transaction data.
        '500':
          description: Internal server error

  /info:
    get:
      summary: Get server info
      description: Retrieve information about the DevServer including RPC URL, port, and account count.
      operationId: getInfo
      tags:
        - info
      responses:
        '200':
          description: Information about the DevServer.
          content:
            application/json:
              schema:
                type: object
                properties:
                  rpcUrl:
                    type: string
                    example: "http://localhost:8545"
                  rpcPort:
                    type: string
                    example: "8545"
                  accountsCount:
                    type: integer
                    example: 10
        '500':
          description: Internal server error
